### ISSUE TITLE
Pattern Modifiers for multiline not working

### ISSUE THREAD

**Issue by coder77** [spatie/regex#14]
May I know how to use the regex with PHP Pattern Modifiers for multiline? 

/i is working but /m is not working.

**Comment by sebastiandedeyne** [comment]
This library doesn't really do anything to your regex, just normalises the way the result is returned, so I don't think this would be an issue with this library.

Could you share a minimal code sample that doesn't work as expected?

**Comment by coder77** [comment]
It's due this issue:

This is equivalent to Perl's /m modifier. If there are no "\n" characters in a subject string, or no occurrences of ^ or $ in a pattern, setting this modifier has no effect.
(http://php.net/manual/en/reference.pcre.pattern.modifiers.php)

Think this issue can close.
