### ISSUE TITLE
Allow default value when group doesn't exist

### ISSUE THREAD

**Issue by luiz-brandao** [spatie/regex#15]
Hey there, I have a sittuation where a regex group might not exist and where  I would like to return a default value instead. With the current implementation I would need to do a check first and handle that accordingly. What if we could specify a default value as a parameter? I was about to submit a PR but I would like some feedback first, let me know if you think this would be useful:

How I do it now:
```php
$pattern = '/some-pattern/(.+?)/with-groups';

if(Regex::match($pattern, $url)->hasMatch()){
    $value = Regex::match($pattern, $url)->group(1);
}) else {
    $value = 'something else';   
};

// or
$regex = Regex::match($pattern, $url);
$value = $regex->hasMatch() ? $regex->group(1) : 'something else';
```
Proposed way:

```php
// this approach would add a default parameter to keep backwards compatibility
$value = Regex::match('/some-pattern/(.+?)/with-groups', $url)->group(1, 'something else');

// or a new method
$value = Regex::match('/some-pattern/(.+?)/with-groups', $url)->groupOr(1, 'something else');

// or maybe simply return null or false?
$value = Regex::match('/some-pattern/(.+?)/with-groups', $url)->group(1) ?? 'something else';
```

Anyway, it might not even be worth it...

**Comment by sebastiandedeyne** [comment]
I like this idea!

I'd accept a tested PR that adds `resultOr` and `groupOr` methods. We can't augment the old ones since that'd be a breaking change.

**Comment by joshuadegier** [comment]
I think this one should be closed @sebastiandedeyne

**Comment by freekmurze** [comment]
Yup
