### ISSUE TITLE
Request: Retrieve array of groups.

### ISSUE THREAD

**Issue by nmsmith22389** [spatie/regex#33]
First of all, I ❤️  this library as well as all of your projects! 🤓 

I think it would be really convenient to be able to access the private `MatchResult::$matches` property to be able to access the results as an array.

### Example
```php
$result = Regex::match($pattern, $subject);

// Either as a property...
$result->matches;

// or as an accessor method...
$result->groups()

// Use
$results = $result->groups();
echo($results[3]); // Printing group #3.
```

Could also probably apply to `MatchAllResult::class` as well.

Thank you for all of your work!

**Comment by sebastiandedeyne** [comment]
I'd accept a tested PR that adds a `groups` method to the `MatchResult` class :)

**Comment by nmsmith22389** [comment]
Thanks!
