### ISSUE TITLE
Cannot replace with `_`

### ISSUE THREAD

**Issue by msiemens** [spatie/regex#37]
Using

```php
Regex::replace('/[^a-zA-Z0-9_]+/', '_', $value)->result();
```

fails with this error message:

```
_() expects parameter 1 to be string, object given
```

It seems like the `_` string is detected as a callable as it may refer to gettext's [`_()` function](https://stackoverflow.com/q/3413920/997063)

**Comment by R3l4x3** [comment]
@freekmurze Is it enough to simply check `$replacement` for an `_`?

**Comment by msiemens** [comment]
Well, it will still break if we use any other method name as a replacement string 🙈

**Comment by jetwes** [comment]
I added a PR for this. I check if it's a callable and if the callable require no parameters. If it requires parameters it will be taken as a string - otherwise as a callabe

**Comment by jetwes** [comment]
> working on a PR that checks if the replacement value is not a string before checking if it is callable

But so it's not possible to use a callable at all....

**Comment by pepijn-de-wachter** [comment]
I (maybe too boldly) assumed it was meant to only accept anonymous functions as in the example in the readme
now that I think about it more, one might want to use the replacement callable to trim the result (or any other existing string function) though in the readme it specifies the passed parameter is of type MatchResult, which no built-in callable would know how to handle, making an anonymous function (to me currently) seemingly the only valid option for replacement with callable

**Comment by jetwes** [comment]
ah ok - fair point...

**Comment by pepijn-de-wachter** [comment]
the only exception would be if you define your own global method somewhere (which in the current days of OOP isn't exactly a best practice) in that case your PR, when modified to check if the callable expects a single parameter of type MatchResult, would actually be the most correct fix, though a simpler check like my PR 'should' have less performance loss than using reflections.
In any case it wasn't a bad thought process in my opinion to check the parameters, I'll leave it up to freek/sebastian to make the call which fix they feel fits best
