### ISSUE TITLE
Expensive

### ISSUE THREAD

**Issue by Sarke** [spatie/regex#48]
Just looking at the documentation:

```php
// Using `match`
Regex::match('/a/', 'abc'); // `MatchResult` object
Regex::match('/a/', 'abc')->hasMatch(); // true
Regex::match('/a/', 'abc')->result(); // 'a'
```

I realize this is an example, but it's not uncommon for regex to be expensive to process, and this static approach would reevaluate the regex for each statement.

An object-oriented approach would be better, or perhaps some caching of results to prevent needlessly processing the same patterns and string combinations more than once.

Alternatively, remove `hasMatch()` and suggest checking the `result()` and `results()` to determine if there are matches.

**Comment by Sarke** [comment]
Is there anything wrong with this? If not, this should be the examples in the docs.

```php
// Using `match`
$result = Regex::match('/a/', 'abc'); // `MatchResult` object
$result->hasMatch(); // true
$result->result(); // 'a'
```

**Comment by sebastiandedeyne** [comment]
The performance difference between the two examples is negligible in most cases. If you're dealing with large blobs of text or complex regexes where performance is key, you probably aren't using this package anyway.
