### ISSUE TITLE
[Discussion] Integrate SRL as option

### ISSUE THREAD

**Issue by okaufmann** [spatie/regex#9]
Does it make sense to integrate https://github.com/TYVRNET/SRL in this package to have one simple Regex API? Regardless if one want to use raw regex or SRL.

**Comment by sebastiandedeyne** [comment]
I wouldn't mind supporting this if it doesn't add to much overhead to the package (similar discussion to #8)

**Comment by lexus27** [comment]
Good Idea, implemented by a bridge

**Comment by sebastiandedeyne** [comment]
Closing this, since I'm not really up to supporting this in this package. If necessary I'd accept PR's to make it easier to extend this package for things like this.
